### ISSUE TITLE
Indeterminate Amelia's stops

### ISSUE THREAD

**Issue by juan3036** [unicesi/amelia#4] opened 2016-01-31 23:56 UTC
I'm using Amelia to execute a series of experiments with fraSCAti. However; sometimes while an experiment is running the execution gets freezed without apparent reason (there are no errors or exceptions) and the experiment has to be stopped and parameterized from this point to start it again. Which forces to be aware of the execution.

Is there any suggestion to avoid this unpredictable behavior?

Thanks

**Comment by jachinte** [comment] 2016-02-01 02:33
Hi @juan3036,
This unpredictable behavior may be a matter of concurrency. It is hard to say what is the problem and how to avoid it without a reproducible example. If you can provide one, I can search for a reason and correct it in case it is necessary. Also, the session logs can be helpful (when the deployment got freezed).

**Comment by jachinte** [comment] 2016-02-24 00:11
Hi @juan3036,
This seems to be gone, so I'm closing it. In case this behavior continues, please let me know.

**Closed as completed by jachinte** 2016-02-24 00:11 UTC
